# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1157-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.srcs/sources_1/new/my_data_type.vhd
  C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.srcs/sources_1/new/Dff.vhd
  C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.srcs/sources_1/new/Basic_Structure_1D.vhd
  C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.srcs/sources_1/new/Basic_Structure_0.vhd
  C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.srcs/sources_1/new/Stage_8_1D.vhd
  C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.srcs/sources_1/new/Stage_8_2D.vhd
  C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.srcs/sources_1/new/Stage_8_4D.vhd
  C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.srcs/sources_1/new/Stage_8_8D.vhd
  C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.srcs/sources_1/new/Basic_Structure_2D.vhd
  C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.srcs/sources_1/new/Basic_Structure_4D.vhd
  C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.srcs/sources_1/new/Basic_Structure_8D.vhd
  C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.srcs/sources_1/new/Stage_8_16D.vhd
  C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.srcs/sources_1/new/Stage_8_32D.vhd
  C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.srcs/sources_1/new/Stage_8_64D.vhd
  C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Efficient_Parallel_Correlator/Efficient_Parallel_Correlator.srcs/sources_1/new/Golay_128.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Golay_128 -part xc7vx690tffg1157-3


write_checkpoint -force -noxdef Golay_128.dcp

catch { report_utilization -file Golay_128_utilization_synth.rpt -pb Golay_128_utilization_synth.pb }
