// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "AA"
#define AUTOTB_TVIN_AA  "../tv/cdatafile/c.MatrixMultiply.autotvin_AA.dat"
// wrapc file define: "bb"
#define AUTOTB_TVIN_bb  "../tv/cdatafile/c.MatrixMultiply.autotvin_bb.dat"
// wrapc file define: "cc"
#define AUTOTB_TVOUT_cc  "../tv/cdatafile/c.MatrixMultiply.autotvout_cc.dat"
#define AUTOTB_TVIN_cc  "../tv/cdatafile/c.MatrixMultiply.autotvin_cc.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "cc"
#define AUTOTB_TVOUT_PC_cc  "../tv/rtldatafile/rtl.MatrixMultiply.autotvout_cc.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			AA_depth = 0;
			bb_depth = 0;
			cc_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{AA " << AA_depth << "}\n";
			total_list << "{bb " << bb_depth << "}\n";
			total_list << "{cc " << cc_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int AA_depth;
		int bb_depth;
		int cc_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern "C" void MatrixMultiply (
int AA[25],
int bb[5],
int cc[5]);

extern "C" void AESL_WRAP_MatrixMultiply (
int AA[25],
int bb[5],
int cc[5])
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "cc"
		aesl_fh.read(AUTOTB_TVOUT_PC_cc, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_cc, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_cc, AESL_token); // data

			sc_bv<32> *cc_pc_buffer = new sc_bv<32>[5];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'cc', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'cc', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					cc_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_cc, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_cc))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: cc
				{
					// bitslice(31, 0)
					// {
						// celement: cc(31, 0)
						// {
							sc_lv<32>* cc_lv0_0_4_1 = new sc_lv<32>[5];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: cc(31, 0)
						{
							// carray: (0) => (4) @ (1)
							for (int i_0 = 0; i_0 <= 4; i_0 += 1)
							{
								if (&(cc[0]) != NULL) // check the null address if the c port is array or others
								{
									cc_lv0_0_4_1[hls_map_index].range(31, 0) = sc_bv<32>(cc_pc_buffer[hls_map_index].range(31, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: cc(31, 0)
						{
							// carray: (0) => (4) @ (1)
							for (int i_0 = 0; i_0 <= 4; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : cc[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : cc[0]
								// output_left_conversion : cc[i_0]
								// output_type_conversion : (cc_lv0_0_4_1[hls_map_index]).to_uint64()
								if (&(cc[0]) != NULL) // check the null address if the c port is array or others
								{
									cc[i_0] = (cc_lv0_0_4_1[hls_map_index]).to_uint64();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] cc_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "AA"
		char* tvin_AA = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_AA);

		// "bb"
		char* tvin_bb = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_bb);

		// "cc"
		char* tvin_cc = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_cc);
		char* tvout_cc = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_cc);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_AA, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_AA, tvin_AA);

		sc_bv<32>* AA_tvin_wrapc_buffer = new sc_bv<32>[25];

		// RTL Name: AA
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: AA(31, 0)
				{
					// carray: (0) => (24) @ (1)
					for (int i_0 = 0; i_0 <= 24; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : AA[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : AA[0]
						// regulate_c_name       : AA
						// input_type_conversion : AA[i_0]
						if (&(AA[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> AA_tmp_mem;
							AA_tmp_mem = AA[i_0];
							AA_tvin_wrapc_buffer[hls_map_index].range(31, 0) = AA_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 25; i++)
		{
			sprintf(tvin_AA, "%s\n", (AA_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_AA, tvin_AA);
		}

		tcl_file.set_num(25, &tcl_file.AA_depth);
		sprintf(tvin_AA, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_AA, tvin_AA);

		// release memory allocation
		delete [] AA_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_bb, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_bb, tvin_bb);

		sc_bv<32>* bb_tvin_wrapc_buffer = new sc_bv<32>[5];

		// RTL Name: bb
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: bb(31, 0)
				{
					// carray: (0) => (4) @ (1)
					for (int i_0 = 0; i_0 <= 4; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : bb[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : bb[0]
						// regulate_c_name       : bb
						// input_type_conversion : bb[i_0]
						if (&(bb[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> bb_tmp_mem;
							bb_tmp_mem = bb[i_0];
							bb_tvin_wrapc_buffer[hls_map_index].range(31, 0) = bb_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 5; i++)
		{
			sprintf(tvin_bb, "%s\n", (bb_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_bb, tvin_bb);
		}

		tcl_file.set_num(5, &tcl_file.bb_depth);
		sprintf(tvin_bb, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_bb, tvin_bb);

		// release memory allocation
		delete [] bb_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_cc, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_cc, tvin_cc);

		sc_bv<32>* cc_tvin_wrapc_buffer = new sc_bv<32>[5];

		// RTL Name: cc
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: cc(31, 0)
				{
					// carray: (0) => (4) @ (1)
					for (int i_0 = 0; i_0 <= 4; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : cc[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : cc[0]
						// regulate_c_name       : cc
						// input_type_conversion : cc[i_0]
						if (&(cc[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> cc_tmp_mem;
							cc_tmp_mem = cc[i_0];
							cc_tvin_wrapc_buffer[hls_map_index].range(31, 0) = cc_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 5; i++)
		{
			sprintf(tvin_cc, "%s\n", (cc_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_cc, tvin_cc);
		}

		tcl_file.set_num(5, &tcl_file.cc_depth);
		sprintf(tvin_cc, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_cc, tvin_cc);

		// release memory allocation
		delete [] cc_tvin_wrapc_buffer;

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		MatrixMultiply(AA, bb, cc);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_cc, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_cc, tvout_cc);

		sc_bv<32>* cc_tvout_wrapc_buffer = new sc_bv<32>[5];

		// RTL Name: cc
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: cc(31, 0)
				{
					// carray: (0) => (4) @ (1)
					for (int i_0 = 0; i_0 <= 4; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : cc[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : cc[0]
						// regulate_c_name       : cc
						// input_type_conversion : cc[i_0]
						if (&(cc[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> cc_tmp_mem;
							cc_tmp_mem = cc[i_0];
							cc_tvout_wrapc_buffer[hls_map_index].range(31, 0) = cc_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 5; i++)
		{
			sprintf(tvout_cc, "%s\n", (cc_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_cc, tvout_cc);
		}

		tcl_file.set_num(5, &tcl_file.cc_depth);
		sprintf(tvout_cc, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_cc, tvout_cc);

		// release memory allocation
		delete [] cc_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "AA"
		delete [] tvin_AA;
		// release memory allocation: "bb"
		delete [] tvin_bb;
		// release memory allocation: "cc"
		delete [] tvout_cc;
		delete [] tvin_cc;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

