# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1157-3
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_vhdl C:/Users/Administrator/Desktop/VHDL_Circuit_Design-master/Example/serial_parallel/serial_parallel.srcs/sources_1/new/serial_parallel.vhd
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/VHDL_Circuit_Design-master/Example/serial_parallel/serial_parallel.data/wt [current_project]
set_property parent.project_dir C:/Users/Administrator/Desktop/VHDL_Circuit_Design-master/Example/serial_parallel [current_project]
synth_design -top serial_parallel -part xc7vx690tffg1157-3
write_checkpoint serial_parallel.dcp
report_utilization -file serial_parallel_utilization_synth.rpt -pb serial_parallel_utilization_synth.pb
