# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/ip/INTF_FIFO/INTF_FIFO.xci
# IP: The module: 'INTF_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/ip/INTF_FIFO/INTF_FIFO/INTF_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'INTF_FIFO'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/ip/INTF_FIFO/INTF_FIFO/INTF_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'INTF_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/ip/INTF_FIFO/INTF_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INTF_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/ip/INTF_FIFO/INTF_FIFO.xci
# IP: The module: 'INTF_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/ip/INTF_FIFO/INTF_FIFO/INTF_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'INTF_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/ip/INTF_FIFO/INTF_FIFO/INTF_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'INTF_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/ip/INTF_FIFO/INTF_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INTF_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
