set_property PACKAGE_PIN AW30 [get_ports a[0]]
set_property IOSTANDARD LVCMOS18 [get_ports a[0]]
set_property PACKAGE_PIN AY30 [get_ports a[1]]
set_property IOSTANDARD LVCMOS18 [get_ports a[1]]
set_property PACKAGE_PIN BA30 [get_ports a[2]]
set_property IOSTANDARD LVCMOS18 [get_ports a[2]]
set_property PACKAGE_PIN BB31 [get_ports a[3]]
set_property IOSTANDARD LVCMOS18 [get_ports a[3]]
set_property PACKAGE_PIN AV30 [get_ports b[0]]
set_property IOSTANDARD LVCMOS18 [get_ports b[0]]
set_property PACKAGE_PIN AY33 [get_ports b[1]]
set_property IOSTANDARD LVCMOS18 [get_ports b[1]]
set_property PACKAGE_PIN BA31 [get_ports b[2]]
set_property IOSTANDARD LVCMOS18 [get_ports b[2]]
set_property PACKAGE_PIN BA32 [get_ports b[3]]
set_property IOSTANDARD LVCMOS18 [get_ports b[3]]
set_property PACKAGE_PIN AM39 [get_ports sum[0]]
set_property IOSTANDARD LVCMOS18 [get_ports sum[0]]
set_property PACKAGE_PIN AN39 [get_ports sum[1]]
set_property IOSTANDARD LVCMOS18 [get_ports sum[1]]
set_property PACKAGE_PIN AR37 [get_ports sum[2]]
set_property IOSTANDARD LVCMOS18 [get_ports sum[2]]
set_property PACKAGE_PIN AT37 [get_ports sum[3]]
set_property IOSTANDARD LVCMOS18 [get_ports sum[3]]
set_property PACKAGE_PIN AR35 [get_ports sum[4]]
set_property IOSTANDARD LVCMOS18 [get_ports sum[4]]


