# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a200tsbg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.cache/wt [current_project]
set_property parent.project_path E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.runs/DDR_FDD_IN_synth_1/DDR_FDD_IN.dcp
set_property used_in_implementation false [get_files E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.runs/DDR_FDD_IN_synth_1/DDR_FDD_IN.dcp]
add_files -quiet E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.runs/INTF_FIFO_synth_1/INTF_FIFO.dcp
set_property used_in_implementation false [get_files E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.runs/INTF_FIFO_synth_1/INTF_FIFO.dcp]
add_files -quiet E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.runs/DDR_FDD_OUT_synth_1/DDR_FDD_OUT.dcp
set_property used_in_implementation false [get_files E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.runs/DDR_FDD_OUT_synth_1/DDR_FDD_OUT.dcp]
add_files -quiet E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
add_files -quiet E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.runs/ila_0_synth_1/ila_0.dcp
set_property used_in_implementation false [get_files E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.runs/ila_0_synth_1/ila_0.dcp]
read_verilog -library xil_defaultlib {
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_SPI_READ_WRITE.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART9_ENSM.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART8_GPO.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART7_CONTROL_OUT.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART6_AUXDAC_AUXADC.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART5_PARALLEL_PORT.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART4_RX_FILTER.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART3_TX_FILTER.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART2_BBPLL.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART22_END_ENABLE_RX_TX.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART21_RSSI_POWER_MEASURE.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART20_TX_ATT.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART19_TX_QUAD_CAL.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART18_ADC_TUNE.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART17_TX_2ND_FILTER.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART16_RX_TIA.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART15_TX_BB_FILTER_TUNE.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART14_RX_BB_FILTER_TUNE.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART13_RX_MANUAL_GAIN.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART12_RX_GAIN_TABLE.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART11_MIXER_SUBTABLE.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART10_RFVCO.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_CONFIG_PART1.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/new/QPSK_I_Q_MAPPER.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/new/BARKER_GEN.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/new/VADJ_SET.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/FREQ_SET_40M.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/RESET.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/PLL_LD_DEJITTER.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_SPI_INTF.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_DATA_INTF_TX.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/AD80305_DATA_INTF_RX.v
  E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/imports/Project_CMOS_FDD/PICO_ICS_FDD.v
}
read_xdc E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/constrs_1/imports/Nexys_Video_XDC/NexysVideo_Master.xdc
set_property used_in_implementation false [get_files E:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/constrs_1/imports/Nexys_Video_XDC/NexysVideo_Master.xdc]

synth_design -top PICO_ICS_FDD -part xc7a200tsbg484-1
write_checkpoint -noxdef PICO_ICS_FDD.dcp
catch { report_utilization -file PICO_ICS_FDD_utilization_synth.rpt -pb PICO_ICS_FDD_utilization_synth.pb }
