# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xq7z045rf676-2I
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_vhdl {
  D:/vivado_project/Correlator/Correlator.srcs/sources_1/new/dff_logic.vhd
  D:/vivado_project/Correlator/Correlator.srcs/sources_1/new/shirt_register_8.vhd
  D:/vivado_project/Correlator/Correlator.srcs/sources_1/new/shirt_register_4.vhd
  D:/vivado_project/Correlator/Correlator.srcs/sources_1/new/shift_register_32.vhd
  D:/vivado_project/Correlator/Correlator.srcs/sources_1/new/shift_register_2.vhd
  D:/vivado_project/Correlator/Correlator.srcs/sources_1/new/shift_register_16.vhd
  D:/vivado_project/Correlator/Correlator.srcs/sources_1/new/shift_register_1.vhd
  D:/vivado_project/Correlator/Correlator.srcs/sources_1/new/Correlator_64.vhd
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_project/Correlator/Correlator.data/wt [current_project]
set_property parent.project_dir D:/vivado_project/Correlator [current_project]
synth_design -top Correlator_64 -part xq7z045rf676-2I
write_checkpoint Correlator_64.dcp
report_utilization -file Correlator_64_utilization_synth.rpt -pb Correlator_64_utilization_synth.pb
