# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Chapter_3/pro1_adder1/pro1_adder1.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Chapter_3/pro1_adder1/pro1_adder1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Administrator/Desktop/VHDL_Circuit_Design/Chapter_3/pro1_adder1/pro1_adder1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Chapter_3/pro1_adder1/pro1_adder1.srcs/sources_1/new/adder2.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Chapter_3/pro1_adder1/pro1_adder1.srcs/constrs_1/new/adder.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/VHDL_Circuit_Design/Chapter_3/pro1_adder1/pro1_adder1.srcs/constrs_1/new/adder.xdc]


synth_design -top adder2 -part xc7vx485tffg1761-2


write_checkpoint -force -noxdef adder2.dcp

catch { report_utilization -file adder2_utilization_synth.rpt -pb adder2_utilization_synth.pb }
