# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/ip/DDR_FDD_IN/DDR_FDD_IN.xci
# IP: The module: 'DDR_FDD_IN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/ip/DDR_FDD_IN/DDR_FDD_IN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR_FDD_IN'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: e:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/ip/DDR_FDD_IN/DDR_FDD_IN.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR_FDD_IN'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: e:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/ip/DDR_FDD_IN/DDR_FDD_IN.xci
# IP: The module: 'DDR_FDD_IN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/ip/DDR_FDD_IN/DDR_FDD_IN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR_FDD_IN'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: e:/Project_CMOS_FDD/project_CMOS_FDD/project_CMOS_FDD.srcs/sources_1/ip/DDR_FDD_IN/DDR_FDD_IN.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR_FDD_IN'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
