// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Efficient_Cor_HH_
#define _Efficient_Cor_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Stage_8_8D.h"
#include "Stage_8_4D.h"
#include "Stage_8_32D.h"
#include "Stage_8_16D.h"
#include "Efficient_Cor_fsubkb.h"
#include "Efficient_Cor_bufeOg.h"
#include "Efficient_Cor_buffYi.h"
#include "Efficient_Cor_bufg8j.h"
#include "Efficient_Cor_bufhbi.h"
#include "Efficient_Cor_bufkbM.h"

namespace ap_rtl {

struct Efficient_Cor : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<3> > Gol_a_address0;
    sc_out< sc_logic > Gol_a_ce0;
    sc_in< sc_lv<32> > Gol_a_q0;
    sc_out< sc_lv<3> > Gol_b_address0;
    sc_out< sc_logic > Gol_b_ce0;
    sc_in< sc_lv<32> > Gol_b_q0;
    sc_out< sc_lv<3> > Gor_a_address0;
    sc_out< sc_logic > Gor_a_ce0;
    sc_out< sc_logic > Gor_a_we0;
    sc_out< sc_lv<32> > Gor_a_d0;
    sc_out< sc_lv<3> > Gor_b_address0;
    sc_out< sc_logic > Gor_b_ce0;
    sc_out< sc_logic > Gor_b_we0;
    sc_out< sc_lv<32> > Gor_b_d0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    Efficient_Cor(sc_module_name name);
    SC_HAS_PROCESS(Efficient_Cor);

    ~Efficient_Cor();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    Efficient_Cor_bufeOg* buf_cor_8D_a_U;
    Efficient_Cor_buffYi* buf_cor_8D_b_U;
    Efficient_Cor_bufg8j* buf_cor_2D_a_U;
    Efficient_Cor_bufhbi* buf_cor_4D_a_U;
    Efficient_Cor_bufhbi* buf_cor_16D_a_U;
    Efficient_Cor_bufhbi* buf_cor_32D_a_U;
    Efficient_Cor_bufkbM* buf_cor_1D_a_U;
    Stage_8_8D* grp_Stage_8_8D_fu_250;
    Stage_8_4D* grp_Stage_8_4D_fu_264;
    Stage_8_32D* grp_Stage_8_32D_fu_280;
    Stage_8_16D* grp_Stage_8_16D_fu_290;
    Efficient_Cor_fsubkb<1,4,32,32,32>* Efficient_Cor_fsubkb_x_U18;
    Efficient_Cor_fsubkb<1,4,32,32,32>* Efficient_Cor_fsubkb_x_U19;
    sc_signal< sc_lv<37> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > dff_1D;
    sc_signal< sc_lv<3> > buf_cor_8D_a_address0;
    sc_signal< sc_logic > buf_cor_8D_a_ce0;
    sc_signal< sc_logic > buf_cor_8D_a_we0;
    sc_signal< sc_lv<32> > buf_cor_8D_a_q0;
    sc_signal< sc_lv<3> > buf_cor_8D_a_address1;
    sc_signal< sc_logic > buf_cor_8D_a_ce1;
    sc_signal< sc_lv<32> > buf_cor_8D_a_q1;
    sc_signal< sc_lv<32> > dff_2D_0;
    sc_signal< sc_lv<32> > dff_2D_1;
    sc_signal< sc_lv<3> > buf_cor_2D_a_address0;
    sc_signal< sc_logic > buf_cor_2D_a_ce0;
    sc_signal< sc_logic > buf_cor_2D_a_we0;
    sc_signal< sc_lv<32> > buf_cor_2D_a_q0;
    sc_signal< sc_lv<3> > buf_cor_2D_a_address1;
    sc_signal< sc_logic > buf_cor_2D_a_ce1;
    sc_signal< sc_logic > buf_cor_2D_a_we1;
    sc_signal< sc_lv<32> > buf_cor_2D_a_q1;
    sc_signal< sc_lv<3> > buf_cor_4D_a_address0;
    sc_signal< sc_logic > buf_cor_4D_a_ce0;
    sc_signal< sc_logic > buf_cor_4D_a_we0;
    sc_signal< sc_lv<32> > buf_cor_4D_a_q0;
    sc_signal< sc_lv<3> > buf_cor_16D_a_address0;
    sc_signal< sc_logic > buf_cor_16D_a_ce0;
    sc_signal< sc_logic > buf_cor_16D_a_we0;
    sc_signal< sc_lv<32> > buf_cor_16D_a_q0;
    sc_signal< sc_lv<3> > buf_cor_32D_a_address0;
    sc_signal< sc_logic > buf_cor_32D_a_ce0;
    sc_signal< sc_logic > buf_cor_32D_a_we0;
    sc_signal< sc_lv<32> > buf_cor_32D_a_q0;
    sc_signal< sc_lv<32> > reg_308;
    sc_signal< sc_lv<1> > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > ap_CS_fsm_state10;
    sc_signal< sc_lv<32> > grp_fu_300_p2;
    sc_signal< sc_lv<32> > reg_313;
    sc_signal< sc_lv<1> > ap_CS_fsm_state7;
    sc_signal< sc_lv<1> > ap_CS_fsm_state14;
    sc_signal< sc_lv<1> > ap_CS_fsm_state22;
    sc_signal< sc_lv<1> > ap_CS_fsm_state29;
    sc_signal< sc_lv<32> > reg_319;
    sc_signal< sc_lv<1> > ap_CS_fsm_state18;
    sc_signal< sc_lv<1> > ap_CS_fsm_state25;
    sc_signal< sc_lv<32> > reg_325;
    sc_signal< sc_lv<3> > indvarinc_fu_336_p2;
    sc_signal< sc_lv<1> > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > tmp_fu_342_p2;
    sc_signal< sc_lv<1> > ap_CS_fsm_state4;
    sc_signal< sc_lv<3> > i_fu_370_p2;
    sc_signal< sc_lv<3> > i_reg_457;
    sc_signal< sc_lv<1> > ap_CS_fsm_state9;
    sc_signal< sc_lv<1> > exitcond1_i_fu_364_p2;
    sc_signal< sc_lv<32> > i_cast_fu_376_p1;
    sc_signal< sc_lv<32> > i_cast_reg_467;
    sc_signal< sc_lv<32> > Gol_b_load_1_reg_477;
    sc_signal< sc_lv<1> > ap_CS_fsm_state19;
    sc_signal< sc_lv<32> > grp_fu_304_p2;
    sc_signal< sc_lv<32> > tmp_i5_reg_492;
    sc_signal< sc_lv<3> > i_4_fu_414_p2;
    sc_signal< sc_lv<3> > i_4_reg_500;
    sc_signal< sc_lv<1> > ap_CS_fsm_state24;
    sc_signal< sc_lv<1> > exitcond1_i7_fu_408_p2;
    sc_signal< sc_lv<32> > sum_i_cast_fu_426_p1;
    sc_signal< sc_lv<32> > sum_i_cast_reg_510;
    sc_signal< sc_lv<3> > buf_cor_1D_a_address0;
    sc_signal< sc_logic > buf_cor_1D_a_ce0;
    sc_signal< sc_logic > buf_cor_1D_a_we0;
    sc_signal< sc_lv<32> > buf_cor_1D_a_d0;
    sc_signal< sc_lv<32> > buf_cor_1D_a_q0;
    sc_signal< sc_logic > grp_Stage_8_8D_fu_250_ap_start;
    sc_signal< sc_logic > grp_Stage_8_8D_fu_250_ap_done;
    sc_signal< sc_logic > grp_Stage_8_8D_fu_250_ap_idle;
    sc_signal< sc_logic > grp_Stage_8_8D_fu_250_ap_ready;
    sc_signal< sc_lv<3> > grp_Stage_8_8D_fu_250_buf_a_address0;
    sc_signal< sc_logic > grp_Stage_8_8D_fu_250_buf_a_ce0;
    sc_signal< sc_lv<32> > grp_Stage_8_8D_fu_250_buf_a_q0;
    sc_signal< sc_lv<3> > grp_Stage_8_8D_fu_250_buf_cor_a_address0;
    sc_signal< sc_logic > grp_Stage_8_8D_fu_250_buf_cor_a_ce0;
    sc_signal< sc_logic > grp_Stage_8_8D_fu_250_buf_cor_a_we0;
    sc_signal< sc_lv<32> > grp_Stage_8_8D_fu_250_buf_cor_a_d0;
    sc_signal< sc_lv<3> > grp_Stage_8_8D_fu_250_buf_cor_b_address0;
    sc_signal< sc_logic > grp_Stage_8_8D_fu_250_buf_cor_b_ce0;
    sc_signal< sc_logic > grp_Stage_8_8D_fu_250_buf_cor_b_we0;
    sc_signal< sc_lv<32> > grp_Stage_8_8D_fu_250_buf_cor_b_d0;
    sc_signal< sc_logic > grp_Stage_8_4D_fu_264_ap_start;
    sc_signal< sc_logic > grp_Stage_8_4D_fu_264_ap_done;
    sc_signal< sc_logic > grp_Stage_8_4D_fu_264_ap_idle;
    sc_signal< sc_logic > grp_Stage_8_4D_fu_264_ap_ready;
    sc_signal< sc_lv<3> > grp_Stage_8_4D_fu_264_buf_a_address0;
    sc_signal< sc_logic > grp_Stage_8_4D_fu_264_buf_a_ce0;
    sc_signal< sc_lv<3> > grp_Stage_8_4D_fu_264_buf_a_address1;
    sc_signal< sc_logic > grp_Stage_8_4D_fu_264_buf_a_ce1;
    sc_signal< sc_lv<3> > grp_Stage_8_4D_fu_264_buf_cor_4D_a_address0;
    sc_signal< sc_logic > grp_Stage_8_4D_fu_264_buf_cor_4D_a_ce0;
    sc_signal< sc_logic > grp_Stage_8_4D_fu_264_buf_cor_4D_a_we0;
    sc_signal< sc_lv<32> > grp_Stage_8_4D_fu_264_buf_cor_4D_a_d0;
    sc_signal< sc_logic > grp_Stage_8_32D_fu_280_ap_start;
    sc_signal< sc_logic > grp_Stage_8_32D_fu_280_ap_done;
    sc_signal< sc_logic > grp_Stage_8_32D_fu_280_ap_idle;
    sc_signal< sc_logic > grp_Stage_8_32D_fu_280_ap_ready;
    sc_signal< sc_lv<3> > grp_Stage_8_32D_fu_280_buf_a_address0;
    sc_signal< sc_logic > grp_Stage_8_32D_fu_280_buf_a_ce0;
    sc_signal< sc_lv<3> > grp_Stage_8_32D_fu_280_buf_cor_32D_a_address0;
    sc_signal< sc_logic > grp_Stage_8_32D_fu_280_buf_cor_32D_a_ce0;
    sc_signal< sc_logic > grp_Stage_8_32D_fu_280_buf_cor_32D_a_we0;
    sc_signal< sc_lv<32> > grp_Stage_8_32D_fu_280_buf_cor_32D_a_d0;
    sc_signal< sc_logic > grp_Stage_8_16D_fu_290_ap_start;
    sc_signal< sc_logic > grp_Stage_8_16D_fu_290_ap_done;
    sc_signal< sc_logic > grp_Stage_8_16D_fu_290_ap_idle;
    sc_signal< sc_logic > grp_Stage_8_16D_fu_290_ap_ready;
    sc_signal< sc_lv<3> > grp_Stage_8_16D_fu_290_buf_a_address0;
    sc_signal< sc_logic > grp_Stage_8_16D_fu_290_buf_a_ce0;
    sc_signal< sc_lv<3> > grp_Stage_8_16D_fu_290_buf_cor_16D_a_address0;
    sc_signal< sc_logic > grp_Stage_8_16D_fu_290_buf_cor_16D_a_ce0;
    sc_signal< sc_logic > grp_Stage_8_16D_fu_290_buf_cor_16D_a_we0;
    sc_signal< sc_lv<32> > grp_Stage_8_16D_fu_290_buf_cor_16D_a_d0;
    sc_signal< sc_lv<3> > invdar_reg_217;
    sc_signal< sc_lv<3> > i_i_reg_228;
    sc_signal< sc_lv<1> > ap_CS_fsm_state8;
    sc_signal< sc_lv<1> > ap_CS_fsm_state15;
    sc_signal< sc_lv<3> > i_i6_reg_239;
    sc_signal< sc_lv<1> > ap_CS_fsm_state23;
    sc_signal< sc_lv<1> > ap_CS_fsm_state30;
    sc_signal< sc_logic > ap_reg_grp_Stage_8_8D_fu_250_ap_start;
    sc_signal< sc_lv<1> > ap_CS_fsm_state36;
    sc_signal< sc_lv<1> > ap_CS_fsm_state16;
    sc_signal< sc_lv<1> > ap_CS_fsm_state37;
    sc_signal< sc_logic > ap_reg_grp_Stage_8_4D_fu_264_ap_start;
    sc_signal< sc_lv<1> > ap_CS_fsm_state31;
    sc_signal< sc_logic > ap_reg_grp_Stage_8_32D_fu_280_ap_start;
    sc_signal< sc_lv<1> > ap_CS_fsm_state34;
    sc_signal< sc_lv<1> > ap_CS_fsm_state35;
    sc_signal< sc_logic > ap_reg_grp_Stage_8_16D_fu_290_ap_start;
    sc_signal< sc_lv<1> > ap_CS_fsm_state32;
    sc_signal< sc_lv<1> > ap_CS_fsm_state33;
    sc_signal< sc_lv<32> > invdar_cast_fu_331_p1;
    sc_signal< sc_lv<32> > i_i_cast2_fu_359_p1;
    sc_signal< sc_lv<32> > i_i6_cast1_fu_403_p1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state17;
    sc_signal< sc_lv<32> > grp_fu_300_p0;
    sc_signal< sc_lv<32> > grp_fu_300_p1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state11;
    sc_signal< sc_lv<1> > ap_CS_fsm_state26;
    sc_signal< sc_lv<3> > sum_i_fu_420_p2;
    sc_signal< sc_lv<37> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<37> ap_ST_fsm_state1;
    static const sc_lv<37> ap_ST_fsm_state2;
    static const sc_lv<37> ap_ST_fsm_state3;
    static const sc_lv<37> ap_ST_fsm_state4;
    static const sc_lv<37> ap_ST_fsm_state5;
    static const sc_lv<37> ap_ST_fsm_state6;
    static const sc_lv<37> ap_ST_fsm_state7;
    static const sc_lv<37> ap_ST_fsm_state8;
    static const sc_lv<37> ap_ST_fsm_state9;
    static const sc_lv<37> ap_ST_fsm_state10;
    static const sc_lv<37> ap_ST_fsm_state11;
    static const sc_lv<37> ap_ST_fsm_state12;
    static const sc_lv<37> ap_ST_fsm_state13;
    static const sc_lv<37> ap_ST_fsm_state14;
    static const sc_lv<37> ap_ST_fsm_state15;
    static const sc_lv<37> ap_ST_fsm_state16;
    static const sc_lv<37> ap_ST_fsm_state17;
    static const sc_lv<37> ap_ST_fsm_state18;
    static const sc_lv<37> ap_ST_fsm_state19;
    static const sc_lv<37> ap_ST_fsm_state20;
    static const sc_lv<37> ap_ST_fsm_state21;
    static const sc_lv<37> ap_ST_fsm_state22;
    static const sc_lv<37> ap_ST_fsm_state23;
    static const sc_lv<37> ap_ST_fsm_state24;
    static const sc_lv<37> ap_ST_fsm_state25;
    static const sc_lv<37> ap_ST_fsm_state26;
    static const sc_lv<37> ap_ST_fsm_state27;
    static const sc_lv<37> ap_ST_fsm_state28;
    static const sc_lv<37> ap_ST_fsm_state29;
    static const sc_lv<37> ap_ST_fsm_state30;
    static const sc_lv<37> ap_ST_fsm_state31;
    static const sc_lv<37> ap_ST_fsm_state32;
    static const sc_lv<37> ap_ST_fsm_state33;
    static const sc_lv<37> ap_ST_fsm_state34;
    static const sc_lv<37> ap_ST_fsm_state35;
    static const sc_lv<37> ap_ST_fsm_state36;
    static const sc_lv<37> ap_ST_fsm_state37;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_23;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_24;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<32> ap_const_lv32_21;
    static const sc_lv<32> ap_const_lv32_22;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_20;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<3> ap_const_lv3_6;
    static const sc_lv<3> ap_const_lv3_7;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<3> ap_const_lv3_2;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_Gol_a_address0();
    void thread_Gol_a_ce0();
    void thread_Gol_b_address0();
    void thread_Gol_b_ce0();
    void thread_Gor_a_address0();
    void thread_Gor_a_ce0();
    void thread_Gor_a_d0();
    void thread_Gor_a_we0();
    void thread_Gor_b_address0();
    void thread_Gor_b_ce0();
    void thread_Gor_b_d0();
    void thread_Gor_b_we0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state22();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state25();
    void thread_ap_CS_fsm_state26();
    void thread_ap_CS_fsm_state29();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state30();
    void thread_ap_CS_fsm_state31();
    void thread_ap_CS_fsm_state32();
    void thread_ap_CS_fsm_state33();
    void thread_ap_CS_fsm_state34();
    void thread_ap_CS_fsm_state35();
    void thread_ap_CS_fsm_state36();
    void thread_ap_CS_fsm_state37();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_buf_cor_16D_a_address0();
    void thread_buf_cor_16D_a_ce0();
    void thread_buf_cor_16D_a_we0();
    void thread_buf_cor_1D_a_address0();
    void thread_buf_cor_1D_a_ce0();
    void thread_buf_cor_1D_a_d0();
    void thread_buf_cor_1D_a_we0();
    void thread_buf_cor_2D_a_address0();
    void thread_buf_cor_2D_a_address1();
    void thread_buf_cor_2D_a_ce0();
    void thread_buf_cor_2D_a_ce1();
    void thread_buf_cor_2D_a_we0();
    void thread_buf_cor_2D_a_we1();
    void thread_buf_cor_32D_a_address0();
    void thread_buf_cor_32D_a_ce0();
    void thread_buf_cor_32D_a_we0();
    void thread_buf_cor_4D_a_address0();
    void thread_buf_cor_4D_a_ce0();
    void thread_buf_cor_4D_a_we0();
    void thread_buf_cor_8D_a_address0();
    void thread_buf_cor_8D_a_address1();
    void thread_buf_cor_8D_a_ce0();
    void thread_buf_cor_8D_a_ce1();
    void thread_buf_cor_8D_a_we0();
    void thread_exitcond1_i7_fu_408_p2();
    void thread_exitcond1_i_fu_364_p2();
    void thread_grp_Stage_8_16D_fu_290_ap_start();
    void thread_grp_Stage_8_32D_fu_280_ap_start();
    void thread_grp_Stage_8_4D_fu_264_ap_start();
    void thread_grp_Stage_8_8D_fu_250_ap_start();
    void thread_grp_Stage_8_8D_fu_250_buf_a_q0();
    void thread_grp_fu_300_p0();
    void thread_grp_fu_300_p1();
    void thread_i_4_fu_414_p2();
    void thread_i_cast_fu_376_p1();
    void thread_i_fu_370_p2();
    void thread_i_i6_cast1_fu_403_p1();
    void thread_i_i_cast2_fu_359_p1();
    void thread_indvarinc_fu_336_p2();
    void thread_invdar_cast_fu_331_p1();
    void thread_sum_i_cast_fu_426_p1();
    void thread_sum_i_fu_420_p2();
    void thread_tmp_fu_342_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
