// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Efficient_Cor.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Efficient_Cor::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Efficient_Cor::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state1 = "1";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state2 = "10";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state3 = "100";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state4 = "1000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state5 = "10000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state6 = "100000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state7 = "1000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state8 = "10000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state9 = "100000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state10 = "1000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state11 = "10000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state12 = "100000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<37> Efficient_Cor::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<32> Efficient_Cor::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> Efficient_Cor::ap_const_lv1_1 = "1";
const sc_lv<32> Efficient_Cor::ap_const_lv32_2 = "10";
const sc_lv<32> Efficient_Cor::ap_const_lv32_9 = "1001";
const sc_lv<32> Efficient_Cor::ap_const_lv32_6 = "110";
const sc_lv<32> Efficient_Cor::ap_const_lv32_D = "1101";
const sc_lv<32> Efficient_Cor::ap_const_lv32_15 = "10101";
const sc_lv<32> Efficient_Cor::ap_const_lv32_1C = "11100";
const sc_lv<32> Efficient_Cor::ap_const_lv32_11 = "10001";
const sc_lv<32> Efficient_Cor::ap_const_lv32_18 = "11000";
const sc_lv<32> Efficient_Cor::ap_const_lv32_1 = "1";
const sc_lv<1> Efficient_Cor::ap_const_lv1_0 = "0";
const sc_lv<32> Efficient_Cor::ap_const_lv32_3 = "11";
const sc_lv<32> Efficient_Cor::ap_const_lv32_8 = "1000";
const sc_lv<32> Efficient_Cor::ap_const_lv32_12 = "10010";
const sc_lv<32> Efficient_Cor::ap_const_lv32_17 = "10111";
const sc_lv<3> Efficient_Cor::ap_const_lv3_0 = "000";
const sc_lv<32> Efficient_Cor::ap_const_lv32_7 = "111";
const sc_lv<32> Efficient_Cor::ap_const_lv32_E = "1110";
const sc_lv<32> Efficient_Cor::ap_const_lv32_16 = "10110";
const sc_lv<32> Efficient_Cor::ap_const_lv32_1D = "11101";
const sc_lv<32> Efficient_Cor::ap_const_lv32_23 = "100011";
const sc_lv<32> Efficient_Cor::ap_const_lv32_F = "1111";
const sc_lv<32> Efficient_Cor::ap_const_lv32_24 = "100100";
const sc_lv<32> Efficient_Cor::ap_const_lv32_1E = "11110";
const sc_lv<32> Efficient_Cor::ap_const_lv32_21 = "100001";
const sc_lv<32> Efficient_Cor::ap_const_lv32_22 = "100010";
const sc_lv<32> Efficient_Cor::ap_const_lv32_1F = "11111";
const sc_lv<32> Efficient_Cor::ap_const_lv32_20 = "100000";
const sc_lv<32> Efficient_Cor::ap_const_lv32_10 = "10000";
const sc_lv<3> Efficient_Cor::ap_const_lv3_1 = "1";
const sc_lv<3> Efficient_Cor::ap_const_lv3_6 = "110";
const sc_lv<3> Efficient_Cor::ap_const_lv3_7 = "111";
const sc_lv<32> Efficient_Cor::ap_const_lv32_A = "1010";
const sc_lv<32> Efficient_Cor::ap_const_lv32_19 = "11001";
const sc_lv<3> Efficient_Cor::ap_const_lv3_2 = "10";

Efficient_Cor::Efficient_Cor(sc_module_name name) : sc_module(name), mVcdFile(0) {
    buf_cor_8D_a_U = new Efficient_Cor_bufeOg("buf_cor_8D_a_U");
    buf_cor_8D_a_U->clk(ap_clk);
    buf_cor_8D_a_U->reset(ap_rst);
    buf_cor_8D_a_U->address0(buf_cor_8D_a_address0);
    buf_cor_8D_a_U->ce0(buf_cor_8D_a_ce0);
    buf_cor_8D_a_U->we0(buf_cor_8D_a_we0);
    buf_cor_8D_a_U->d0(grp_Stage_8_8D_fu_250_buf_cor_a_d0);
    buf_cor_8D_a_U->q0(buf_cor_8D_a_q0);
    buf_cor_8D_a_U->address1(buf_cor_8D_a_address1);
    buf_cor_8D_a_U->ce1(buf_cor_8D_a_ce1);
    buf_cor_8D_a_U->q1(buf_cor_8D_a_q1);
    buf_cor_8D_b_U = new Efficient_Cor_buffYi("buf_cor_8D_b_U");
    buf_cor_8D_b_U->clk(ap_clk);
    buf_cor_8D_b_U->reset(ap_rst);
    buf_cor_8D_b_U->address0(grp_Stage_8_8D_fu_250_buf_cor_b_address0);
    buf_cor_8D_b_U->ce0(grp_Stage_8_8D_fu_250_buf_cor_b_ce0);
    buf_cor_8D_b_U->we0(grp_Stage_8_8D_fu_250_buf_cor_b_we0);
    buf_cor_8D_b_U->d0(grp_Stage_8_8D_fu_250_buf_cor_b_d0);
    buf_cor_2D_a_U = new Efficient_Cor_bufg8j("buf_cor_2D_a_U");
    buf_cor_2D_a_U->clk(ap_clk);
    buf_cor_2D_a_U->reset(ap_rst);
    buf_cor_2D_a_U->address0(buf_cor_2D_a_address0);
    buf_cor_2D_a_U->ce0(buf_cor_2D_a_ce0);
    buf_cor_2D_a_U->we0(buf_cor_2D_a_we0);
    buf_cor_2D_a_U->d0(reg_313);
    buf_cor_2D_a_U->q0(buf_cor_2D_a_q0);
    buf_cor_2D_a_U->address1(buf_cor_2D_a_address1);
    buf_cor_2D_a_U->ce1(buf_cor_2D_a_ce1);
    buf_cor_2D_a_U->we1(buf_cor_2D_a_we1);
    buf_cor_2D_a_U->d1(tmp_i5_reg_492);
    buf_cor_2D_a_U->q1(buf_cor_2D_a_q1);
    buf_cor_4D_a_U = new Efficient_Cor_bufhbi("buf_cor_4D_a_U");
    buf_cor_4D_a_U->clk(ap_clk);
    buf_cor_4D_a_U->reset(ap_rst);
    buf_cor_4D_a_U->address0(buf_cor_4D_a_address0);
    buf_cor_4D_a_U->ce0(buf_cor_4D_a_ce0);
    buf_cor_4D_a_U->we0(buf_cor_4D_a_we0);
    buf_cor_4D_a_U->d0(grp_Stage_8_4D_fu_264_buf_cor_4D_a_d0);
    buf_cor_4D_a_U->q0(buf_cor_4D_a_q0);
    buf_cor_16D_a_U = new Efficient_Cor_bufhbi("buf_cor_16D_a_U");
    buf_cor_16D_a_U->clk(ap_clk);
    buf_cor_16D_a_U->reset(ap_rst);
    buf_cor_16D_a_U->address0(buf_cor_16D_a_address0);
    buf_cor_16D_a_U->ce0(buf_cor_16D_a_ce0);
    buf_cor_16D_a_U->we0(buf_cor_16D_a_we0);
    buf_cor_16D_a_U->d0(grp_Stage_8_16D_fu_290_buf_cor_16D_a_d0);
    buf_cor_16D_a_U->q0(buf_cor_16D_a_q0);
    buf_cor_32D_a_U = new Efficient_Cor_bufhbi("buf_cor_32D_a_U");
    buf_cor_32D_a_U->clk(ap_clk);
    buf_cor_32D_a_U->reset(ap_rst);
    buf_cor_32D_a_U->address0(buf_cor_32D_a_address0);
    buf_cor_32D_a_U->ce0(buf_cor_32D_a_ce0);
    buf_cor_32D_a_U->we0(buf_cor_32D_a_we0);
    buf_cor_32D_a_U->d0(grp_Stage_8_32D_fu_280_buf_cor_32D_a_d0);
    buf_cor_32D_a_U->q0(buf_cor_32D_a_q0);
    buf_cor_1D_a_U = new Efficient_Cor_bufkbM("buf_cor_1D_a_U");
    buf_cor_1D_a_U->clk(ap_clk);
    buf_cor_1D_a_U->reset(ap_rst);
    buf_cor_1D_a_U->address0(buf_cor_1D_a_address0);
    buf_cor_1D_a_U->ce0(buf_cor_1D_a_ce0);
    buf_cor_1D_a_U->we0(buf_cor_1D_a_we0);
    buf_cor_1D_a_U->d0(buf_cor_1D_a_d0);
    buf_cor_1D_a_U->q0(buf_cor_1D_a_q0);
    grp_Stage_8_8D_fu_250 = new Stage_8_8D("grp_Stage_8_8D_fu_250");
    grp_Stage_8_8D_fu_250->ap_clk(ap_clk);
    grp_Stage_8_8D_fu_250->ap_rst(ap_rst);
    grp_Stage_8_8D_fu_250->ap_start(grp_Stage_8_8D_fu_250_ap_start);
    grp_Stage_8_8D_fu_250->ap_done(grp_Stage_8_8D_fu_250_ap_done);
    grp_Stage_8_8D_fu_250->ap_idle(grp_Stage_8_8D_fu_250_ap_idle);
    grp_Stage_8_8D_fu_250->ap_ready(grp_Stage_8_8D_fu_250_ap_ready);
    grp_Stage_8_8D_fu_250->buf_a_address0(grp_Stage_8_8D_fu_250_buf_a_address0);
    grp_Stage_8_8D_fu_250->buf_a_ce0(grp_Stage_8_8D_fu_250_buf_a_ce0);
    grp_Stage_8_8D_fu_250->buf_a_q0(grp_Stage_8_8D_fu_250_buf_a_q0);
    grp_Stage_8_8D_fu_250->buf_cor_a_address0(grp_Stage_8_8D_fu_250_buf_cor_a_address0);
    grp_Stage_8_8D_fu_250->buf_cor_a_ce0(grp_Stage_8_8D_fu_250_buf_cor_a_ce0);
    grp_Stage_8_8D_fu_250->buf_cor_a_we0(grp_Stage_8_8D_fu_250_buf_cor_a_we0);
    grp_Stage_8_8D_fu_250->buf_cor_a_d0(grp_Stage_8_8D_fu_250_buf_cor_a_d0);
    grp_Stage_8_8D_fu_250->buf_cor_b_address0(grp_Stage_8_8D_fu_250_buf_cor_b_address0);
    grp_Stage_8_8D_fu_250->buf_cor_b_ce0(grp_Stage_8_8D_fu_250_buf_cor_b_ce0);
    grp_Stage_8_8D_fu_250->buf_cor_b_we0(grp_Stage_8_8D_fu_250_buf_cor_b_we0);
    grp_Stage_8_8D_fu_250->buf_cor_b_d0(grp_Stage_8_8D_fu_250_buf_cor_b_d0);
    grp_Stage_8_4D_fu_264 = new Stage_8_4D("grp_Stage_8_4D_fu_264");
    grp_Stage_8_4D_fu_264->ap_clk(ap_clk);
    grp_Stage_8_4D_fu_264->ap_rst(ap_rst);
    grp_Stage_8_4D_fu_264->ap_start(grp_Stage_8_4D_fu_264_ap_start);
    grp_Stage_8_4D_fu_264->ap_done(grp_Stage_8_4D_fu_264_ap_done);
    grp_Stage_8_4D_fu_264->ap_idle(grp_Stage_8_4D_fu_264_ap_idle);
    grp_Stage_8_4D_fu_264->ap_ready(grp_Stage_8_4D_fu_264_ap_ready);
    grp_Stage_8_4D_fu_264->buf_a_address0(grp_Stage_8_4D_fu_264_buf_a_address0);
    grp_Stage_8_4D_fu_264->buf_a_ce0(grp_Stage_8_4D_fu_264_buf_a_ce0);
    grp_Stage_8_4D_fu_264->buf_a_q0(buf_cor_2D_a_q0);
    grp_Stage_8_4D_fu_264->buf_a_address1(grp_Stage_8_4D_fu_264_buf_a_address1);
    grp_Stage_8_4D_fu_264->buf_a_ce1(grp_Stage_8_4D_fu_264_buf_a_ce1);
    grp_Stage_8_4D_fu_264->buf_a_q1(buf_cor_2D_a_q1);
    grp_Stage_8_4D_fu_264->buf_cor_4D_a_address0(grp_Stage_8_4D_fu_264_buf_cor_4D_a_address0);
    grp_Stage_8_4D_fu_264->buf_cor_4D_a_ce0(grp_Stage_8_4D_fu_264_buf_cor_4D_a_ce0);
    grp_Stage_8_4D_fu_264->buf_cor_4D_a_we0(grp_Stage_8_4D_fu_264_buf_cor_4D_a_we0);
    grp_Stage_8_4D_fu_264->buf_cor_4D_a_d0(grp_Stage_8_4D_fu_264_buf_cor_4D_a_d0);
    grp_Stage_8_32D_fu_280 = new Stage_8_32D("grp_Stage_8_32D_fu_280");
    grp_Stage_8_32D_fu_280->ap_clk(ap_clk);
    grp_Stage_8_32D_fu_280->ap_rst(ap_rst);
    grp_Stage_8_32D_fu_280->ap_start(grp_Stage_8_32D_fu_280_ap_start);
    grp_Stage_8_32D_fu_280->ap_done(grp_Stage_8_32D_fu_280_ap_done);
    grp_Stage_8_32D_fu_280->ap_idle(grp_Stage_8_32D_fu_280_ap_idle);
    grp_Stage_8_32D_fu_280->ap_ready(grp_Stage_8_32D_fu_280_ap_ready);
    grp_Stage_8_32D_fu_280->buf_a_address0(grp_Stage_8_32D_fu_280_buf_a_address0);
    grp_Stage_8_32D_fu_280->buf_a_ce0(grp_Stage_8_32D_fu_280_buf_a_ce0);
    grp_Stage_8_32D_fu_280->buf_a_q0(buf_cor_16D_a_q0);
    grp_Stage_8_32D_fu_280->buf_cor_32D_a_address0(grp_Stage_8_32D_fu_280_buf_cor_32D_a_address0);
    grp_Stage_8_32D_fu_280->buf_cor_32D_a_ce0(grp_Stage_8_32D_fu_280_buf_cor_32D_a_ce0);
    grp_Stage_8_32D_fu_280->buf_cor_32D_a_we0(grp_Stage_8_32D_fu_280_buf_cor_32D_a_we0);
    grp_Stage_8_32D_fu_280->buf_cor_32D_a_d0(grp_Stage_8_32D_fu_280_buf_cor_32D_a_d0);
    grp_Stage_8_16D_fu_290 = new Stage_8_16D("grp_Stage_8_16D_fu_290");
    grp_Stage_8_16D_fu_290->ap_clk(ap_clk);
    grp_Stage_8_16D_fu_290->ap_rst(ap_rst);
    grp_Stage_8_16D_fu_290->ap_start(grp_Stage_8_16D_fu_290_ap_start);
    grp_Stage_8_16D_fu_290->ap_done(grp_Stage_8_16D_fu_290_ap_done);
    grp_Stage_8_16D_fu_290->ap_idle(grp_Stage_8_16D_fu_290_ap_idle);
    grp_Stage_8_16D_fu_290->ap_ready(grp_Stage_8_16D_fu_290_ap_ready);
    grp_Stage_8_16D_fu_290->buf_a_address0(grp_Stage_8_16D_fu_290_buf_a_address0);
    grp_Stage_8_16D_fu_290->buf_a_ce0(grp_Stage_8_16D_fu_290_buf_a_ce0);
    grp_Stage_8_16D_fu_290->buf_a_q0(buf_cor_4D_a_q0);
    grp_Stage_8_16D_fu_290->buf_cor_16D_a_address0(grp_Stage_8_16D_fu_290_buf_cor_16D_a_address0);
    grp_Stage_8_16D_fu_290->buf_cor_16D_a_ce0(grp_Stage_8_16D_fu_290_buf_cor_16D_a_ce0);
    grp_Stage_8_16D_fu_290->buf_cor_16D_a_we0(grp_Stage_8_16D_fu_290_buf_cor_16D_a_we0);
    grp_Stage_8_16D_fu_290->buf_cor_16D_a_d0(grp_Stage_8_16D_fu_290_buf_cor_16D_a_d0);
    Efficient_Cor_fsubkb_x_U18 = new Efficient_Cor_fsubkb<1,4,32,32,32>("Efficient_Cor_fsubkb_x_U18");
    Efficient_Cor_fsubkb_x_U18->clk(ap_clk);
    Efficient_Cor_fsubkb_x_U18->reset(ap_rst);
    Efficient_Cor_fsubkb_x_U18->din0(grp_fu_300_p0);
    Efficient_Cor_fsubkb_x_U18->din1(grp_fu_300_p1);
    Efficient_Cor_fsubkb_x_U18->ce(ap_var_for_const0);
    Efficient_Cor_fsubkb_x_U18->dout(grp_fu_300_p2);
    Efficient_Cor_fsubkb_x_U19 = new Efficient_Cor_fsubkb<1,4,32,32,32>("Efficient_Cor_fsubkb_x_U19");
    Efficient_Cor_fsubkb_x_U19->clk(ap_clk);
    Efficient_Cor_fsubkb_x_U19->reset(ap_rst);
    Efficient_Cor_fsubkb_x_U19->din0(dff_2D_1);
    Efficient_Cor_fsubkb_x_U19->din1(reg_325);
    Efficient_Cor_fsubkb_x_U19->ce(ap_var_for_const0);
    Efficient_Cor_fsubkb_x_U19->dout(grp_fu_304_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Gol_a_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( i_cast_fu_376_p1 );

    SC_METHOD(thread_Gol_a_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_Gol_b_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( i_i_cast2_fu_359_p1 );

    SC_METHOD(thread_Gol_b_ce0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_Gor_a_address0);
    sensitive << ( grp_Stage_8_8D_fu_250_buf_cor_a_address0 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_Gor_a_ce0);
    sensitive << ( grp_Stage_8_8D_fu_250_buf_cor_a_ce0 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_Gor_a_d0);
    sensitive << ( grp_Stage_8_8D_fu_250_buf_cor_a_d0 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_Gor_a_we0);
    sensitive << ( grp_Stage_8_8D_fu_250_buf_cor_a_we0 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_Gor_b_address0);
    sensitive << ( grp_Stage_8_8D_fu_250_buf_cor_b_address0 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_Gor_b_ce0);
    sensitive << ( grp_Stage_8_8D_fu_250_buf_cor_b_ce0 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_Gor_b_d0);
    sensitive << ( grp_Stage_8_8D_fu_250_buf_cor_b_d0 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_Gor_b_we0);
    sensitive << ( grp_Stage_8_8D_fu_250_buf_cor_b_we0 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state30);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state32);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state33);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state34);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state35);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state36);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state37);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( grp_Stage_8_8D_fu_250_ap_done );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_Stage_8_8D_fu_250_ap_done );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_buf_cor_16D_a_address0);
    sensitive << ( grp_Stage_8_32D_fu_280_buf_a_address0 );
    sensitive << ( grp_Stage_8_16D_fu_290_buf_cor_16D_a_address0 );
    sensitive << ( ap_CS_fsm_state35 );
    sensitive << ( ap_CS_fsm_state33 );

    SC_METHOD(thread_buf_cor_16D_a_ce0);
    sensitive << ( grp_Stage_8_32D_fu_280_buf_a_ce0 );
    sensitive << ( grp_Stage_8_16D_fu_290_buf_cor_16D_a_ce0 );
    sensitive << ( ap_CS_fsm_state35 );
    sensitive << ( ap_CS_fsm_state33 );

    SC_METHOD(thread_buf_cor_16D_a_we0);
    sensitive << ( grp_Stage_8_16D_fu_290_buf_cor_16D_a_we0 );
    sensitive << ( ap_CS_fsm_state33 );

    SC_METHOD(thread_buf_cor_1D_a_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_cast_reg_467 );
    sensitive << ( grp_Stage_8_8D_fu_250_buf_a_address0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( invdar_cast_fu_331_p1 );

    SC_METHOD(thread_buf_cor_1D_a_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_Stage_8_8D_fu_250_buf_a_ce0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_buf_cor_1D_a_d0);
    sensitive << ( reg_313 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_buf_cor_1D_a_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_buf_cor_2D_a_address0);
    sensitive << ( sum_i_cast_reg_510 );
    sensitive << ( grp_Stage_8_4D_fu_264_buf_a_address0 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_buf_cor_2D_a_address1);
    sensitive << ( grp_Stage_8_4D_fu_264_buf_a_address1 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_buf_cor_2D_a_ce0);
    sensitive << ( grp_Stage_8_4D_fu_264_buf_a_ce0 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_buf_cor_2D_a_ce1);
    sensitive << ( grp_Stage_8_4D_fu_264_buf_a_ce1 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_buf_cor_2D_a_we0);
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( ap_CS_fsm_state30 );

    SC_METHOD(thread_buf_cor_2D_a_we1);
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_buf_cor_32D_a_address0);
    sensitive << ( grp_Stage_8_8D_fu_250_buf_a_address0 );
    sensitive << ( grp_Stage_8_32D_fu_280_buf_cor_32D_a_address0 );
    sensitive << ( ap_CS_fsm_state37 );
    sensitive << ( ap_CS_fsm_state35 );

    SC_METHOD(thread_buf_cor_32D_a_ce0);
    sensitive << ( grp_Stage_8_8D_fu_250_buf_a_ce0 );
    sensitive << ( grp_Stage_8_32D_fu_280_buf_cor_32D_a_ce0 );
    sensitive << ( ap_CS_fsm_state37 );
    sensitive << ( ap_CS_fsm_state35 );

    SC_METHOD(thread_buf_cor_32D_a_we0);
    sensitive << ( grp_Stage_8_32D_fu_280_buf_cor_32D_a_we0 );
    sensitive << ( ap_CS_fsm_state35 );

    SC_METHOD(thread_buf_cor_4D_a_address0);
    sensitive << ( grp_Stage_8_4D_fu_264_buf_cor_4D_a_address0 );
    sensitive << ( grp_Stage_8_16D_fu_290_buf_a_address0 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state33 );

    SC_METHOD(thread_buf_cor_4D_a_ce0);
    sensitive << ( grp_Stage_8_4D_fu_264_buf_cor_4D_a_ce0 );
    sensitive << ( grp_Stage_8_16D_fu_290_buf_a_ce0 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state33 );

    SC_METHOD(thread_buf_cor_4D_a_we0);
    sensitive << ( grp_Stage_8_4D_fu_264_buf_cor_4D_a_we0 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_buf_cor_8D_a_address0);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( grp_Stage_8_8D_fu_250_buf_cor_a_address0 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( i_i6_cast1_fu_403_p1 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_buf_cor_8D_a_address1);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( sum_i_cast_fu_426_p1 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_buf_cor_8D_a_ce0);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( grp_Stage_8_8D_fu_250_buf_cor_a_ce0 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_buf_cor_8D_a_ce1);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_buf_cor_8D_a_we0);
    sensitive << ( grp_Stage_8_8D_fu_250_buf_cor_a_we0 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_exitcond1_i7_fu_408_p2);
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( i_i6_reg_239 );

    SC_METHOD(thread_exitcond1_i_fu_364_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( i_i_reg_228 );

    SC_METHOD(thread_grp_Stage_8_16D_fu_290_ap_start);
    sensitive << ( ap_reg_grp_Stage_8_16D_fu_290_ap_start );

    SC_METHOD(thread_grp_Stage_8_32D_fu_280_ap_start);
    sensitive << ( ap_reg_grp_Stage_8_32D_fu_280_ap_start );

    SC_METHOD(thread_grp_Stage_8_4D_fu_264_ap_start);
    sensitive << ( ap_reg_grp_Stage_8_4D_fu_264_ap_start );

    SC_METHOD(thread_grp_Stage_8_8D_fu_250_ap_start);
    sensitive << ( ap_reg_grp_Stage_8_8D_fu_250_ap_start );

    SC_METHOD(thread_grp_Stage_8_8D_fu_250_buf_a_q0);
    sensitive << ( buf_cor_32D_a_q0 );
    sensitive << ( buf_cor_1D_a_q0 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_grp_fu_300_p0);
    sensitive << ( dff_1D );
    sensitive << ( dff_2D_0 );
    sensitive << ( reg_319 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( Gol_b_load_1_reg_477 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_grp_fu_300_p1);
    sensitive << ( reg_308 );
    sensitive << ( reg_319 );
    sensitive << ( reg_325 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_i_4_fu_414_p2);
    sensitive << ( i_i6_reg_239 );

    SC_METHOD(thread_i_cast_fu_376_p1);
    sensitive << ( i_fu_370_p2 );

    SC_METHOD(thread_i_fu_370_p2);
    sensitive << ( i_i_reg_228 );

    SC_METHOD(thread_i_i6_cast1_fu_403_p1);
    sensitive << ( i_i6_reg_239 );

    SC_METHOD(thread_i_i_cast2_fu_359_p1);
    sensitive << ( i_i_reg_228 );

    SC_METHOD(thread_indvarinc_fu_336_p2);
    sensitive << ( invdar_reg_217 );

    SC_METHOD(thread_invdar_cast_fu_331_p1);
    sensitive << ( invdar_reg_217 );

    SC_METHOD(thread_sum_i_cast_fu_426_p1);
    sensitive << ( sum_i_fu_420_p2 );

    SC_METHOD(thread_sum_i_fu_420_p2);
    sensitive << ( i_i6_reg_239 );

    SC_METHOD(thread_tmp_fu_342_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( invdar_reg_217 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_fu_342_p2 );
    sensitive << ( exitcond1_i_fu_364_p2 );
    sensitive << ( exitcond1_i7_fu_408_p2 );
    sensitive << ( grp_Stage_8_8D_fu_250_ap_done );
    sensitive << ( grp_Stage_8_4D_fu_264_ap_done );
    sensitive << ( grp_Stage_8_32D_fu_280_ap_done );
    sensitive << ( grp_Stage_8_16D_fu_290_ap_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000000000000000000000000001";
    dff_1D = "00000000000000000000000000000000";
    dff_2D_0 = "00000000000000000000000000000000";
    dff_2D_1 = "00000000000000000000000000000000";
    ap_reg_grp_Stage_8_8D_fu_250_ap_start = SC_LOGIC_0;
    ap_reg_grp_Stage_8_4D_fu_264_ap_start = SC_LOGIC_0;
    ap_reg_grp_Stage_8_32D_fu_280_ap_start = SC_LOGIC_0;
    ap_reg_grp_Stage_8_16D_fu_290_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Efficient_Cor_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, Gol_a_address0, "(port)Gol_a_address0");
    sc_trace(mVcdFile, Gol_a_ce0, "(port)Gol_a_ce0");
    sc_trace(mVcdFile, Gol_a_q0, "(port)Gol_a_q0");
    sc_trace(mVcdFile, Gol_b_address0, "(port)Gol_b_address0");
    sc_trace(mVcdFile, Gol_b_ce0, "(port)Gol_b_ce0");
    sc_trace(mVcdFile, Gol_b_q0, "(port)Gol_b_q0");
    sc_trace(mVcdFile, Gor_a_address0, "(port)Gor_a_address0");
    sc_trace(mVcdFile, Gor_a_ce0, "(port)Gor_a_ce0");
    sc_trace(mVcdFile, Gor_a_we0, "(port)Gor_a_we0");
    sc_trace(mVcdFile, Gor_a_d0, "(port)Gor_a_d0");
    sc_trace(mVcdFile, Gor_b_address0, "(port)Gor_b_address0");
    sc_trace(mVcdFile, Gor_b_ce0, "(port)Gor_b_ce0");
    sc_trace(mVcdFile, Gor_b_we0, "(port)Gor_b_we0");
    sc_trace(mVcdFile, Gor_b_d0, "(port)Gor_b_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, dff_1D, "dff_1D");
    sc_trace(mVcdFile, buf_cor_8D_a_address0, "buf_cor_8D_a_address0");
    sc_trace(mVcdFile, buf_cor_8D_a_ce0, "buf_cor_8D_a_ce0");
    sc_trace(mVcdFile, buf_cor_8D_a_we0, "buf_cor_8D_a_we0");
    sc_trace(mVcdFile, buf_cor_8D_a_q0, "buf_cor_8D_a_q0");
    sc_trace(mVcdFile, buf_cor_8D_a_address1, "buf_cor_8D_a_address1");
    sc_trace(mVcdFile, buf_cor_8D_a_ce1, "buf_cor_8D_a_ce1");
    sc_trace(mVcdFile, buf_cor_8D_a_q1, "buf_cor_8D_a_q1");
    sc_trace(mVcdFile, dff_2D_0, "dff_2D_0");
    sc_trace(mVcdFile, dff_2D_1, "dff_2D_1");
    sc_trace(mVcdFile, buf_cor_2D_a_address0, "buf_cor_2D_a_address0");
    sc_trace(mVcdFile, buf_cor_2D_a_ce0, "buf_cor_2D_a_ce0");
    sc_trace(mVcdFile, buf_cor_2D_a_we0, "buf_cor_2D_a_we0");
    sc_trace(mVcdFile, buf_cor_2D_a_q0, "buf_cor_2D_a_q0");
    sc_trace(mVcdFile, buf_cor_2D_a_address1, "buf_cor_2D_a_address1");
    sc_trace(mVcdFile, buf_cor_2D_a_ce1, "buf_cor_2D_a_ce1");
    sc_trace(mVcdFile, buf_cor_2D_a_we1, "buf_cor_2D_a_we1");
    sc_trace(mVcdFile, buf_cor_2D_a_q1, "buf_cor_2D_a_q1");
    sc_trace(mVcdFile, buf_cor_4D_a_address0, "buf_cor_4D_a_address0");
    sc_trace(mVcdFile, buf_cor_4D_a_ce0, "buf_cor_4D_a_ce0");
    sc_trace(mVcdFile, buf_cor_4D_a_we0, "buf_cor_4D_a_we0");
    sc_trace(mVcdFile, buf_cor_4D_a_q0, "buf_cor_4D_a_q0");
    sc_trace(mVcdFile, buf_cor_16D_a_address0, "buf_cor_16D_a_address0");
    sc_trace(mVcdFile, buf_cor_16D_a_ce0, "buf_cor_16D_a_ce0");
    sc_trace(mVcdFile, buf_cor_16D_a_we0, "buf_cor_16D_a_we0");
    sc_trace(mVcdFile, buf_cor_16D_a_q0, "buf_cor_16D_a_q0");
    sc_trace(mVcdFile, buf_cor_32D_a_address0, "buf_cor_32D_a_address0");
    sc_trace(mVcdFile, buf_cor_32D_a_ce0, "buf_cor_32D_a_ce0");
    sc_trace(mVcdFile, buf_cor_32D_a_we0, "buf_cor_32D_a_we0");
    sc_trace(mVcdFile, buf_cor_32D_a_q0, "buf_cor_32D_a_q0");
    sc_trace(mVcdFile, reg_308, "reg_308");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_fu_300_p2, "grp_fu_300_p2");
    sc_trace(mVcdFile, reg_313, "reg_313");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, ap_CS_fsm_state29, "ap_CS_fsm_state29");
    sc_trace(mVcdFile, reg_319, "reg_319");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, reg_325, "reg_325");
    sc_trace(mVcdFile, indvarinc_fu_336_p2, "indvarinc_fu_336_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_342_p2, "tmp_fu_342_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, i_fu_370_p2, "i_fu_370_p2");
    sc_trace(mVcdFile, i_reg_457, "i_reg_457");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, exitcond1_i_fu_364_p2, "exitcond1_i_fu_364_p2");
    sc_trace(mVcdFile, i_cast_fu_376_p1, "i_cast_fu_376_p1");
    sc_trace(mVcdFile, i_cast_reg_467, "i_cast_reg_467");
    sc_trace(mVcdFile, Gol_b_load_1_reg_477, "Gol_b_load_1_reg_477");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, grp_fu_304_p2, "grp_fu_304_p2");
    sc_trace(mVcdFile, tmp_i5_reg_492, "tmp_i5_reg_492");
    sc_trace(mVcdFile, i_4_fu_414_p2, "i_4_fu_414_p2");
    sc_trace(mVcdFile, i_4_reg_500, "i_4_reg_500");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, exitcond1_i7_fu_408_p2, "exitcond1_i7_fu_408_p2");
    sc_trace(mVcdFile, sum_i_cast_fu_426_p1, "sum_i_cast_fu_426_p1");
    sc_trace(mVcdFile, sum_i_cast_reg_510, "sum_i_cast_reg_510");
    sc_trace(mVcdFile, buf_cor_1D_a_address0, "buf_cor_1D_a_address0");
    sc_trace(mVcdFile, buf_cor_1D_a_ce0, "buf_cor_1D_a_ce0");
    sc_trace(mVcdFile, buf_cor_1D_a_we0, "buf_cor_1D_a_we0");
    sc_trace(mVcdFile, buf_cor_1D_a_d0, "buf_cor_1D_a_d0");
    sc_trace(mVcdFile, buf_cor_1D_a_q0, "buf_cor_1D_a_q0");
    sc_trace(mVcdFile, grp_Stage_8_8D_fu_250_ap_start, "grp_Stage_8_8D_fu_250_ap_start");
    sc_trace(mVcdFile, grp_Stage_8_8D_fu_250_ap_done, "grp_Stage_8_8D_fu_250_ap_done");
    sc_trace(mVcdFile, grp_Stage_8_8D_fu_250_ap_idle, "grp_Stage_8_8D_fu_250_ap_idle");
    sc_trace(mVcdFile, grp_Stage_8_8D_fu_250_ap_ready, "grp_Stage_8_8D_fu_250_ap_ready");
    sc_trace(mVcdFile, grp_Stage_8_8D_fu_250_buf_a_address0, "grp_Stage_8_8D_fu_250_buf_a_address0");
    sc_trace(mVcdFile, grp_Stage_8_8D_fu_250_buf_a_ce0, "grp_Stage_8_8D_fu_250_buf_a_ce0");
    sc_trace(mVcdFile, grp_Stage_8_8D_fu_250_buf_a_q0, "grp_Stage_8_8D_fu_250_buf_a_q0");
    sc_trace(mVcdFile, grp_Stage_8_8D_fu_250_buf_cor_a_address0, "grp_Stage_8_8D_fu_250_buf_cor_a_address0");
    sc_trace(mVcdFile, grp_Stage_8_8D_fu_250_buf_cor_a_ce0, "grp_Stage_8_8D_fu_250_buf_cor_a_ce0");
    sc_trace(mVcdFile, grp_Stage_8_8D_fu_250_buf_cor_a_we0, "grp_Stage_8_8D_fu_250_buf_cor_a_we0");
    sc_trace(mVcdFile, grp_Stage_8_8D_fu_250_buf_cor_a_d0, "grp_Stage_8_8D_fu_250_buf_cor_a_d0");
    sc_trace(mVcdFile, grp_Stage_8_8D_fu_250_buf_cor_b_address0, "grp_Stage_8_8D_fu_250_buf_cor_b_address0");
    sc_trace(mVcdFile, grp_Stage_8_8D_fu_250_buf_cor_b_ce0, "grp_Stage_8_8D_fu_250_buf_cor_b_ce0");
    sc_trace(mVcdFile, grp_Stage_8_8D_fu_250_buf_cor_b_we0, "grp_Stage_8_8D_fu_250_buf_cor_b_we0");
    sc_trace(mVcdFile, grp_Stage_8_8D_fu_250_buf_cor_b_d0, "grp_Stage_8_8D_fu_250_buf_cor_b_d0");
    sc_trace(mVcdFile, grp_Stage_8_4D_fu_264_ap_start, "grp_Stage_8_4D_fu_264_ap_start");
    sc_trace(mVcdFile, grp_Stage_8_4D_fu_264_ap_done, "grp_Stage_8_4D_fu_264_ap_done");
    sc_trace(mVcdFile, grp_Stage_8_4D_fu_264_ap_idle, "grp_Stage_8_4D_fu_264_ap_idle");
    sc_trace(mVcdFile, grp_Stage_8_4D_fu_264_ap_ready, "grp_Stage_8_4D_fu_264_ap_ready");
    sc_trace(mVcdFile, grp_Stage_8_4D_fu_264_buf_a_address0, "grp_Stage_8_4D_fu_264_buf_a_address0");
    sc_trace(mVcdFile, grp_Stage_8_4D_fu_264_buf_a_ce0, "grp_Stage_8_4D_fu_264_buf_a_ce0");
    sc_trace(mVcdFile, grp_Stage_8_4D_fu_264_buf_a_address1, "grp_Stage_8_4D_fu_264_buf_a_address1");
    sc_trace(mVcdFile, grp_Stage_8_4D_fu_264_buf_a_ce1, "grp_Stage_8_4D_fu_264_buf_a_ce1");
    sc_trace(mVcdFile, grp_Stage_8_4D_fu_264_buf_cor_4D_a_address0, "grp_Stage_8_4D_fu_264_buf_cor_4D_a_address0");
    sc_trace(mVcdFile, grp_Stage_8_4D_fu_264_buf_cor_4D_a_ce0, "grp_Stage_8_4D_fu_264_buf_cor_4D_a_ce0");
    sc_trace(mVcdFile, grp_Stage_8_4D_fu_264_buf_cor_4D_a_we0, "grp_Stage_8_4D_fu_264_buf_cor_4D_a_we0");
    sc_trace(mVcdFile, grp_Stage_8_4D_fu_264_buf_cor_4D_a_d0, "grp_Stage_8_4D_fu_264_buf_cor_4D_a_d0");
    sc_trace(mVcdFile, grp_Stage_8_32D_fu_280_ap_start, "grp_Stage_8_32D_fu_280_ap_start");
    sc_trace(mVcdFile, grp_Stage_8_32D_fu_280_ap_done, "grp_Stage_8_32D_fu_280_ap_done");
    sc_trace(mVcdFile, grp_Stage_8_32D_fu_280_ap_idle, "grp_Stage_8_32D_fu_280_ap_idle");
    sc_trace(mVcdFile, grp_Stage_8_32D_fu_280_ap_ready, "grp_Stage_8_32D_fu_280_ap_ready");
    sc_trace(mVcdFile, grp_Stage_8_32D_fu_280_buf_a_address0, "grp_Stage_8_32D_fu_280_buf_a_address0");
    sc_trace(mVcdFile, grp_Stage_8_32D_fu_280_buf_a_ce0, "grp_Stage_8_32D_fu_280_buf_a_ce0");
    sc_trace(mVcdFile, grp_Stage_8_32D_fu_280_buf_cor_32D_a_address0, "grp_Stage_8_32D_fu_280_buf_cor_32D_a_address0");
    sc_trace(mVcdFile, grp_Stage_8_32D_fu_280_buf_cor_32D_a_ce0, "grp_Stage_8_32D_fu_280_buf_cor_32D_a_ce0");
    sc_trace(mVcdFile, grp_Stage_8_32D_fu_280_buf_cor_32D_a_we0, "grp_Stage_8_32D_fu_280_buf_cor_32D_a_we0");
    sc_trace(mVcdFile, grp_Stage_8_32D_fu_280_buf_cor_32D_a_d0, "grp_Stage_8_32D_fu_280_buf_cor_32D_a_d0");
    sc_trace(mVcdFile, grp_Stage_8_16D_fu_290_ap_start, "grp_Stage_8_16D_fu_290_ap_start");
    sc_trace(mVcdFile, grp_Stage_8_16D_fu_290_ap_done, "grp_Stage_8_16D_fu_290_ap_done");
    sc_trace(mVcdFile, grp_Stage_8_16D_fu_290_ap_idle, "grp_Stage_8_16D_fu_290_ap_idle");
    sc_trace(mVcdFile, grp_Stage_8_16D_fu_290_ap_ready, "grp_Stage_8_16D_fu_290_ap_ready");
    sc_trace(mVcdFile, grp_Stage_8_16D_fu_290_buf_a_address0, "grp_Stage_8_16D_fu_290_buf_a_address0");
    sc_trace(mVcdFile, grp_Stage_8_16D_fu_290_buf_a_ce0, "grp_Stage_8_16D_fu_290_buf_a_ce0");
    sc_trace(mVcdFile, grp_Stage_8_16D_fu_290_buf_cor_16D_a_address0, "grp_Stage_8_16D_fu_290_buf_cor_16D_a_address0");
    sc_trace(mVcdFile, grp_Stage_8_16D_fu_290_buf_cor_16D_a_ce0, "grp_Stage_8_16D_fu_290_buf_cor_16D_a_ce0");
    sc_trace(mVcdFile, grp_Stage_8_16D_fu_290_buf_cor_16D_a_we0, "grp_Stage_8_16D_fu_290_buf_cor_16D_a_we0");
    sc_trace(mVcdFile, grp_Stage_8_16D_fu_290_buf_cor_16D_a_d0, "grp_Stage_8_16D_fu_290_buf_cor_16D_a_d0");
    sc_trace(mVcdFile, invdar_reg_217, "invdar_reg_217");
    sc_trace(mVcdFile, i_i_reg_228, "i_i_reg_228");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, i_i6_reg_239, "i_i6_reg_239");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, ap_CS_fsm_state30, "ap_CS_fsm_state30");
    sc_trace(mVcdFile, ap_reg_grp_Stage_8_8D_fu_250_ap_start, "ap_reg_grp_Stage_8_8D_fu_250_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state36, "ap_CS_fsm_state36");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, ap_CS_fsm_state37, "ap_CS_fsm_state37");
    sc_trace(mVcdFile, ap_reg_grp_Stage_8_4D_fu_264_ap_start, "ap_reg_grp_Stage_8_4D_fu_264_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state31, "ap_CS_fsm_state31");
    sc_trace(mVcdFile, ap_reg_grp_Stage_8_32D_fu_280_ap_start, "ap_reg_grp_Stage_8_32D_fu_280_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state34, "ap_CS_fsm_state34");
    sc_trace(mVcdFile, ap_CS_fsm_state35, "ap_CS_fsm_state35");
    sc_trace(mVcdFile, ap_reg_grp_Stage_8_16D_fu_290_ap_start, "ap_reg_grp_Stage_8_16D_fu_290_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state32, "ap_CS_fsm_state32");
    sc_trace(mVcdFile, ap_CS_fsm_state33, "ap_CS_fsm_state33");
    sc_trace(mVcdFile, invdar_cast_fu_331_p1, "invdar_cast_fu_331_p1");
    sc_trace(mVcdFile, i_i_cast2_fu_359_p1, "i_i_cast2_fu_359_p1");
    sc_trace(mVcdFile, i_i6_cast1_fu_403_p1, "i_i6_cast1_fu_403_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, grp_fu_300_p0, "grp_fu_300_p0");
    sc_trace(mVcdFile, grp_fu_300_p1, "grp_fu_300_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, sum_i_fu_420_p2, "sum_i_fu_420_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("Efficient_Cor.hdltvin.dat");
    mHdltvoutHandle.open("Efficient_Cor.hdltvout.dat");
}

Efficient_Cor::~Efficient_Cor() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete buf_cor_8D_a_U;
    delete buf_cor_8D_b_U;
    delete buf_cor_2D_a_U;
    delete buf_cor_4D_a_U;
    delete buf_cor_16D_a_U;
    delete buf_cor_32D_a_U;
    delete buf_cor_1D_a_U;
    delete grp_Stage_8_8D_fu_250;
    delete grp_Stage_8_4D_fu_264;
    delete grp_Stage_8_32D_fu_280;
    delete grp_Stage_8_16D_fu_290;
    delete Efficient_Cor_fsubkb_x_U18;
    delete Efficient_Cor_fsubkb_x_U19;
}

void Efficient_Cor::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void Efficient_Cor::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_Stage_8_16D_fu_290_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state32.read()))) {
            ap_reg_grp_Stage_8_16D_fu_290_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_Stage_8_16D_fu_290_ap_ready.read())) {
            ap_reg_grp_Stage_8_16D_fu_290_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_Stage_8_32D_fu_280_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state34.read()))) {
            ap_reg_grp_Stage_8_32D_fu_280_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_Stage_8_32D_fu_280_ap_ready.read())) {
            ap_reg_grp_Stage_8_32D_fu_280_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_Stage_8_4D_fu_264_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state24.read()) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i7_fu_408_p2.read()))) {
            ap_reg_grp_Stage_8_4D_fu_264_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_Stage_8_4D_fu_264_ap_ready.read())) {
            ap_reg_grp_Stage_8_4D_fu_264_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_Stage_8_8D_fu_250_ap_start = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()) && 
              !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_fu_364_p2.read())) || 
             (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state36.read())))) {
            ap_reg_grp_Stage_8_8D_fu_250_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_Stage_8_8D_fu_250_ap_ready.read())) {
            ap_reg_grp_Stage_8_8D_fu_250_ap_start = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state30.read()))) {
        i_i6_reg_239 = i_4_reg_500.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read()))) {
        i_i6_reg_239 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read()))) {
        i_i_reg_228 = i_reg_457.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        i_i_reg_228 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_342_p2.read(), ap_const_lv1_0))) {
        invdar_reg_217 = indvarinc_fu_336_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        invdar_reg_217 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read()))) {
        Gol_b_load_1_reg_477 = Gol_b_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        dff_1D = Gol_b_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read()))) {
        dff_2D_0 = buf_cor_8D_a_q0.read();
        dff_2D_1 = buf_cor_8D_a_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state24.read()))) {
        i_4_reg_500 = i_4_fu_414_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_fu_364_p2.read()))) {
        i_cast_reg_467 = i_cast_fu_376_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()))) {
        i_reg_457 = i_fu_370_p2.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read())) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read())))) {
        reg_308 = Gol_a_q0.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read())) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read())) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state29.read())))) {
        reg_313 = grp_fu_300_p2.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state18.read())) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state25.read())))) {
        reg_319 = buf_cor_8D_a_q0.read();
        reg_325 = buf_cor_8D_a_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state24.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i7_fu_408_p2.read()))) {
        sum_i_cast_reg_510 = sum_i_cast_fu_426_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()))) {
        tmp_i5_reg_492 = grp_fu_304_p2.read();
    }
}

void Efficient_Cor::thread_Gol_a_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()))) {
        Gol_a_address0 =  (sc_lv<3>) (i_cast_fu_376_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        Gol_a_address0 =  (sc_lv<3>) (ap_const_lv32_0);
    } else {
        Gol_a_address0 = "XXX";
    }
}

void Efficient_Cor::thread_Gol_a_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())))) {
        Gol_a_ce0 = ap_const_logic_1;
    } else {
        Gol_a_ce0 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_Gol_b_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()))) {
        Gol_b_address0 =  (sc_lv<3>) (i_i_cast2_fu_359_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()))) {
        Gol_b_address0 =  (sc_lv<3>) (ap_const_lv32_7);
    } else {
        Gol_b_address0 = "XXX";
    }
}

void Efficient_Cor::thread_Gol_b_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())))) {
        Gol_b_ce0 = ap_const_logic_1;
    } else {
        Gol_b_ce0 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_Gor_a_address0() {
    Gor_a_address0 = grp_Stage_8_8D_fu_250_buf_cor_a_address0.read();
}

void Efficient_Cor::thread_Gor_a_ce0() {
    Gor_a_ce0 = grp_Stage_8_8D_fu_250_buf_cor_a_ce0.read();
}

void Efficient_Cor::thread_Gor_a_d0() {
    Gor_a_d0 = grp_Stage_8_8D_fu_250_buf_cor_a_d0.read();
}

void Efficient_Cor::thread_Gor_a_we0() {
    Gor_a_we0 = grp_Stage_8_8D_fu_250_buf_cor_a_we0.read();
}

void Efficient_Cor::thread_Gor_b_address0() {
    Gor_b_address0 = grp_Stage_8_8D_fu_250_buf_cor_b_address0.read();
}

void Efficient_Cor::thread_Gor_b_ce0() {
    Gor_b_ce0 = grp_Stage_8_8D_fu_250_buf_cor_b_ce0.read();
}

void Efficient_Cor::thread_Gor_b_d0() {
    Gor_b_d0 = grp_Stage_8_8D_fu_250_buf_cor_b_d0.read();
}

void Efficient_Cor::thread_Gor_b_we0() {
    Gor_b_we0 = grp_Stage_8_8D_fu_250_buf_cor_b_we0.read();
}

void Efficient_Cor::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void Efficient_Cor::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read().range(9, 9);
}

void Efficient_Cor::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read().range(10, 10);
}

void Efficient_Cor::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read().range(13, 13);
}

void Efficient_Cor::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read().range(14, 14);
}

void Efficient_Cor::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read().range(15, 15);
}

void Efficient_Cor::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read().range(16, 16);
}

void Efficient_Cor::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read().range(17, 17);
}

void Efficient_Cor::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read().range(18, 18);
}

void Efficient_Cor::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read().range(1, 1);
}

void Efficient_Cor::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read().range(21, 21);
}

void Efficient_Cor::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read().range(22, 22);
}

void Efficient_Cor::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read().range(23, 23);
}

void Efficient_Cor::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read().range(24, 24);
}

void Efficient_Cor::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read().range(25, 25);
}

void Efficient_Cor::thread_ap_CS_fsm_state29() {
    ap_CS_fsm_state29 = ap_CS_fsm.read().range(28, 28);
}

void Efficient_Cor::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read().range(2, 2);
}

void Efficient_Cor::thread_ap_CS_fsm_state30() {
    ap_CS_fsm_state30 = ap_CS_fsm.read().range(29, 29);
}

void Efficient_Cor::thread_ap_CS_fsm_state31() {
    ap_CS_fsm_state31 = ap_CS_fsm.read().range(30, 30);
}

void Efficient_Cor::thread_ap_CS_fsm_state32() {
    ap_CS_fsm_state32 = ap_CS_fsm.read().range(31, 31);
}

void Efficient_Cor::thread_ap_CS_fsm_state33() {
    ap_CS_fsm_state33 = ap_CS_fsm.read().range(32, 32);
}

void Efficient_Cor::thread_ap_CS_fsm_state34() {
    ap_CS_fsm_state34 = ap_CS_fsm.read().range(33, 33);
}

void Efficient_Cor::thread_ap_CS_fsm_state35() {
    ap_CS_fsm_state35 = ap_CS_fsm.read().range(34, 34);
}

void Efficient_Cor::thread_ap_CS_fsm_state36() {
    ap_CS_fsm_state36 = ap_CS_fsm.read().range(35, 35);
}

void Efficient_Cor::thread_ap_CS_fsm_state37() {
    ap_CS_fsm_state37 = ap_CS_fsm.read().range(36, 36);
}

void Efficient_Cor::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read().range(3, 3);
}

void Efficient_Cor::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read().range(6, 6);
}

void Efficient_Cor::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read().range(7, 7);
}

void Efficient_Cor::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read().range(8, 8);
}

void Efficient_Cor::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state37.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_Stage_8_8D_fu_250_ap_done.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state37.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_Stage_8_8D_fu_250_ap_done.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_buf_cor_16D_a_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state33.read()))) {
        buf_cor_16D_a_address0 = grp_Stage_8_16D_fu_290_buf_cor_16D_a_address0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state35.read()))) {
        buf_cor_16D_a_address0 = grp_Stage_8_32D_fu_280_buf_a_address0.read();
    } else {
        buf_cor_16D_a_address0 = "XXX";
    }
}

void Efficient_Cor::thread_buf_cor_16D_a_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state33.read()))) {
        buf_cor_16D_a_ce0 = grp_Stage_8_16D_fu_290_buf_cor_16D_a_ce0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state35.read()))) {
        buf_cor_16D_a_ce0 = grp_Stage_8_32D_fu_280_buf_a_ce0.read();
    } else {
        buf_cor_16D_a_ce0 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_buf_cor_16D_a_we0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state33.read()))) {
        buf_cor_16D_a_we0 = grp_Stage_8_16D_fu_290_buf_cor_16D_a_we0.read();
    } else {
        buf_cor_16D_a_we0 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_buf_cor_1D_a_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read()))) {
        buf_cor_1D_a_address0 =  (sc_lv<3>) (i_cast_reg_467.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        buf_cor_1D_a_address0 =  (sc_lv<3>) (ap_const_lv32_0);
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        buf_cor_1D_a_address0 =  (sc_lv<3>) (invdar_cast_fu_331_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read()))) {
        buf_cor_1D_a_address0 = grp_Stage_8_8D_fu_250_buf_a_address0.read();
    } else {
        buf_cor_1D_a_address0 = "XXX";
    }
}

void Efficient_Cor::thread_buf_cor_1D_a_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read())))) {
        buf_cor_1D_a_ce0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read()))) {
        buf_cor_1D_a_ce0 = grp_Stage_8_8D_fu_250_buf_a_ce0.read();
    } else {
        buf_cor_1D_a_ce0 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_buf_cor_1D_a_d0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read())))) {
        buf_cor_1D_a_d0 = reg_313.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        buf_cor_1D_a_d0 = ap_const_lv32_0;
    } else {
        buf_cor_1D_a_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Efficient_Cor::thread_buf_cor_1D_a_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read())))) {
        buf_cor_1D_a_we0 = ap_const_logic_1;
    } else {
        buf_cor_1D_a_we0 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_buf_cor_2D_a_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state30.read()))) {
        buf_cor_2D_a_address0 =  (sc_lv<3>) (sum_i_cast_reg_510.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read()))) {
        buf_cor_2D_a_address0 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state31.read()))) {
        buf_cor_2D_a_address0 = grp_Stage_8_4D_fu_264_buf_a_address0.read();
    } else {
        buf_cor_2D_a_address0 = "XXX";
    }
}

void Efficient_Cor::thread_buf_cor_2D_a_address1() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read()))) {
        buf_cor_2D_a_address1 = ap_const_lv3_1;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state31.read()))) {
        buf_cor_2D_a_address1 = grp_Stage_8_4D_fu_264_buf_a_address1.read();
    } else {
        buf_cor_2D_a_address1 = "XXX";
    }
}

void Efficient_Cor::thread_buf_cor_2D_a_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state30.read())))) {
        buf_cor_2D_a_ce0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state31.read()))) {
        buf_cor_2D_a_ce0 = grp_Stage_8_4D_fu_264_buf_a_ce0.read();
    } else {
        buf_cor_2D_a_ce0 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_buf_cor_2D_a_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read()))) {
        buf_cor_2D_a_ce1 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state31.read()))) {
        buf_cor_2D_a_ce1 = grp_Stage_8_4D_fu_264_buf_a_ce1.read();
    } else {
        buf_cor_2D_a_ce1 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_buf_cor_2D_a_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state30.read())))) {
        buf_cor_2D_a_we0 = ap_const_logic_1;
    } else {
        buf_cor_2D_a_we0 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_buf_cor_2D_a_we1() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read())))) {
        buf_cor_2D_a_we1 = ap_const_logic_1;
    } else {
        buf_cor_2D_a_we1 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_buf_cor_32D_a_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state35.read()))) {
        buf_cor_32D_a_address0 = grp_Stage_8_32D_fu_280_buf_cor_32D_a_address0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state37.read()))) {
        buf_cor_32D_a_address0 = grp_Stage_8_8D_fu_250_buf_a_address0.read();
    } else {
        buf_cor_32D_a_address0 = "XXX";
    }
}

void Efficient_Cor::thread_buf_cor_32D_a_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state35.read()))) {
        buf_cor_32D_a_ce0 = grp_Stage_8_32D_fu_280_buf_cor_32D_a_ce0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state37.read()))) {
        buf_cor_32D_a_ce0 = grp_Stage_8_8D_fu_250_buf_a_ce0.read();
    } else {
        buf_cor_32D_a_ce0 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_buf_cor_32D_a_we0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state35.read()))) {
        buf_cor_32D_a_we0 = grp_Stage_8_32D_fu_280_buf_cor_32D_a_we0.read();
    } else {
        buf_cor_32D_a_we0 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_buf_cor_4D_a_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state33.read()))) {
        buf_cor_4D_a_address0 = grp_Stage_8_16D_fu_290_buf_a_address0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state31.read()))) {
        buf_cor_4D_a_address0 = grp_Stage_8_4D_fu_264_buf_cor_4D_a_address0.read();
    } else {
        buf_cor_4D_a_address0 = "XXX";
    }
}

void Efficient_Cor::thread_buf_cor_4D_a_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state33.read()))) {
        buf_cor_4D_a_ce0 = grp_Stage_8_16D_fu_290_buf_a_ce0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state31.read()))) {
        buf_cor_4D_a_ce0 = grp_Stage_8_4D_fu_264_buf_cor_4D_a_ce0.read();
    } else {
        buf_cor_4D_a_ce0 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_buf_cor_4D_a_we0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state31.read()))) {
        buf_cor_4D_a_we0 = grp_Stage_8_4D_fu_264_buf_cor_4D_a_we0.read();
    } else {
        buf_cor_4D_a_we0 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_buf_cor_8D_a_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state24.read()))) {
        buf_cor_8D_a_address0 =  (sc_lv<3>) (i_i6_cast1_fu_403_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()))) {
        buf_cor_8D_a_address0 = ap_const_lv3_6;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state17.read()))) {
        buf_cor_8D_a_address0 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read()))) {
        buf_cor_8D_a_address0 = grp_Stage_8_8D_fu_250_buf_cor_a_address0.read();
    } else {
        buf_cor_8D_a_address0 = "XXX";
    }
}

void Efficient_Cor::thread_buf_cor_8D_a_address1() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state24.read()))) {
        buf_cor_8D_a_address1 =  (sc_lv<3>) (sum_i_cast_fu_426_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()))) {
        buf_cor_8D_a_address1 = ap_const_lv3_7;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state17.read()))) {
        buf_cor_8D_a_address1 = ap_const_lv3_1;
    } else {
        buf_cor_8D_a_address1 = "XXX";
    }
}

void Efficient_Cor::thread_buf_cor_8D_a_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state24.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state17.read())))) {
        buf_cor_8D_a_ce0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read()))) {
        buf_cor_8D_a_ce0 = grp_Stage_8_8D_fu_250_buf_cor_a_ce0.read();
    } else {
        buf_cor_8D_a_ce0 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_buf_cor_8D_a_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state24.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state17.read())))) {
        buf_cor_8D_a_ce1 = ap_const_logic_1;
    } else {
        buf_cor_8D_a_ce1 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_buf_cor_8D_a_we0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read()))) {
        buf_cor_8D_a_we0 = grp_Stage_8_8D_fu_250_buf_cor_a_we0.read();
    } else {
        buf_cor_8D_a_we0 = ap_const_logic_0;
    }
}

void Efficient_Cor::thread_exitcond1_i7_fu_408_p2() {
    exitcond1_i7_fu_408_p2 = (!i_i6_reg_239.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(i_i6_reg_239.read() == ap_const_lv3_6);
}

void Efficient_Cor::thread_exitcond1_i_fu_364_p2() {
    exitcond1_i_fu_364_p2 = (!i_i_reg_228.read().is_01() || !ap_const_lv3_7.is_01())? sc_lv<1>(): sc_lv<1>(i_i_reg_228.read() == ap_const_lv3_7);
}

void Efficient_Cor::thread_grp_Stage_8_16D_fu_290_ap_start() {
    grp_Stage_8_16D_fu_290_ap_start = ap_reg_grp_Stage_8_16D_fu_290_ap_start.read();
}

void Efficient_Cor::thread_grp_Stage_8_32D_fu_280_ap_start() {
    grp_Stage_8_32D_fu_280_ap_start = ap_reg_grp_Stage_8_32D_fu_280_ap_start.read();
}

void Efficient_Cor::thread_grp_Stage_8_4D_fu_264_ap_start() {
    grp_Stage_8_4D_fu_264_ap_start = ap_reg_grp_Stage_8_4D_fu_264_ap_start.read();
}

void Efficient_Cor::thread_grp_Stage_8_8D_fu_250_ap_start() {
    grp_Stage_8_8D_fu_250_ap_start = ap_reg_grp_Stage_8_8D_fu_250_ap_start.read();
}

void Efficient_Cor::thread_grp_Stage_8_8D_fu_250_buf_a_q0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state37.read()))) {
        grp_Stage_8_8D_fu_250_buf_a_q0 = buf_cor_32D_a_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read()))) {
        grp_Stage_8_8D_fu_250_buf_a_q0 = buf_cor_1D_a_q0.read();
    } else {
        grp_Stage_8_8D_fu_250_buf_a_q0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Efficient_Cor::thread_grp_fu_300_p0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state26.read()))) {
        grp_fu_300_p0 = reg_319.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state19.read()))) {
        grp_fu_300_p0 = dff_2D_0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read()))) {
        grp_fu_300_p0 = Gol_b_load_1_reg_477.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        grp_fu_300_p0 = dff_1D.read();
    } else {
        grp_fu_300_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Efficient_Cor::thread_grp_fu_300_p1() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state26.read()))) {
        grp_fu_300_p1 = reg_325.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state19.read()))) {
        grp_fu_300_p1 = reg_319.read();
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read())))) {
        grp_fu_300_p1 = reg_308.read();
    } else {
        grp_fu_300_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Efficient_Cor::thread_i_4_fu_414_p2() {
    i_4_fu_414_p2 = (!i_i6_reg_239.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_i6_reg_239.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void Efficient_Cor::thread_i_cast_fu_376_p1() {
    i_cast_fu_376_p1 = esl_zext<32,3>(i_fu_370_p2.read());
}

void Efficient_Cor::thread_i_fu_370_p2() {
    i_fu_370_p2 = (!i_i_reg_228.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_i_reg_228.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void Efficient_Cor::thread_i_i6_cast1_fu_403_p1() {
    i_i6_cast1_fu_403_p1 = esl_zext<32,3>(i_i6_reg_239.read());
}

void Efficient_Cor::thread_i_i_cast2_fu_359_p1() {
    i_i_cast2_fu_359_p1 = esl_zext<32,3>(i_i_reg_228.read());
}

void Efficient_Cor::thread_indvarinc_fu_336_p2() {
    indvarinc_fu_336_p2 = (!invdar_reg_217.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(invdar_reg_217.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void Efficient_Cor::thread_invdar_cast_fu_331_p1() {
    invdar_cast_fu_331_p1 = esl_zext<32,3>(invdar_reg_217.read());
}

void Efficient_Cor::thread_sum_i_cast_fu_426_p1() {
    sum_i_cast_fu_426_p1 = esl_zext<32,3>(sum_i_fu_420_p2.read());
}

void Efficient_Cor::thread_sum_i_fu_420_p2() {
    sum_i_fu_420_p2 = (!i_i6_reg_239.read().is_01() || !ap_const_lv3_2.is_01())? sc_lv<3>(): (sc_biguint<3>(i_i6_reg_239.read()) + sc_biguint<3>(ap_const_lv3_2));
}

void Efficient_Cor::thread_tmp_fu_342_p2() {
    tmp_fu_342_p2 = (!invdar_reg_217.read().is_01() || !ap_const_lv3_7.is_01())? sc_lv<1>(): sc_lv<1>(invdar_reg_217.read() == ap_const_lv3_7);
}

void Efficient_Cor::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(tmp_fu_342_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_fu_364_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state16;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 32768 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_Stage_8_8D_fu_250_ap_done.read())) {
                ap_NS_fsm = ap_ST_fsm_state17;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i7_fu_408_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state31;
            } else {
                ap_NS_fsm = ap_ST_fsm_state25;
            }
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 1073741824 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_Stage_8_4D_fu_264_ap_done.read())) {
                ap_NS_fsm = ap_ST_fsm_state32;
            } else {
                ap_NS_fsm = ap_ST_fsm_state31;
            }
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_Stage_8_16D_fu_290_ap_done.read())) {
                ap_NS_fsm = ap_ST_fsm_state34;
            } else {
                ap_NS_fsm = ap_ST_fsm_state33;
            }
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_Stage_8_32D_fu_280_ap_done.read())) {
                ap_NS_fsm = ap_ST_fsm_state36;
            } else {
                ap_NS_fsm = ap_ST_fsm_state35;
            }
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_Stage_8_8D_fu_250_ap_done.read())) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state37;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<37>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void Efficient_Cor::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Gol_a_address0\" :  \"" << Gol_a_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Gol_a_ce0\" :  \"" << Gol_a_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Gol_a_q0\" :  \"" << Gol_a_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Gol_b_address0\" :  \"" << Gol_b_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Gol_b_ce0\" :  \"" << Gol_b_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Gol_b_q0\" :  \"" << Gol_b_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Gor_a_address0\" :  \"" << Gor_a_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Gor_a_ce0\" :  \"" << Gor_a_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Gor_a_we0\" :  \"" << Gor_a_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Gor_a_d0\" :  \"" << Gor_a_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Gor_b_address0\" :  \"" << Gor_b_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Gor_b_ce0\" :  \"" << Gor_b_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Gor_b_we0\" :  \"" << Gor_b_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Gor_b_d0\" :  \"" << Gor_b_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

